### ISSUE TITLE
QueryParamPlaceHolder doesn't work with single quote

### ISSUE THREAD

**Issue by dmgcodevil** [jmingo-projects/jmingo#10]
Example:

``` java
Criteria criteria = Criteria
                .where("{ 'date' : { '$gt' : '#date'} }")
                .with("date", date);
QueryParamPlaceHolder.replaceQueryParameters(queryTemplate, parameters);
```

Stack trace:

```
java.lang.StackOverflowError
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:444)
    at java.lang.StringBuffer.append(StringBuffer.java:312)
    at java.lang.StringBuffer.append(StringBuffer.java:97)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:459)
    at java.lang.StringBuffer.append(StringBuffer.java:340)
    at java.util.regex.Matcher.appendReplacement(Matcher.java:890)
    at java.util.regex.Matcher.replaceAll(Matcher.java:955)
    at java.lang.String.replace(String.java:2227)
    at com.mingo.query.QueryParamPlaceHolder.removeParameters(QueryParamPlaceHolder.java:55)
    at 
....
```

**Comment by dmgcodevil** [comment]
closed [26](https://github.com/dmgcodevil/mingo/commit/899475396225c03bc0335f3c24063f7f578b180d)
